hash-format = "sha256"

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "833fe74ca806f98e6d0da2fbc413e229f1328c47b9b65485cfd653235383467c"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "3213c881d019cd8f952f738c10d5a950ee52ff0084750b81f656a58a4a78515d"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ea336d25c3e21ef168aec20e1ea470c96949ad29632646ee8e8ab0d74b4bbfc9"
metafile = true

[[files]]
file = "mods/bellsandwhistles.pw.toml"
hash = "e1f4a53e3e52b534add5dd018597fefd345d9bd6350b9c46ef0ec281fc62af8e"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "8fde54624913d86f1176cd1086fa485f1a872573dac144347c57cab76596b715"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "cde21d14fcaf9495f0f5b3d8fb298dd60cb12badc21a27414c25ebf11dfb3fe1"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "bf463928645c586cb57a4e02533ee300af3931cf9db9233dae7efc1826643d41"
metafile = true

[[files]]
file = "mods/create-central-kitchen.pw.toml"
hash = "8cd33949146121a4522626672939679c49b79e2353b6ba34fcb5fbcef0e4fd91"
metafile = true

[[files]]
file = "mods/create-connected.pw.toml"
hash = "e5e2f1cbb38c22d86c08dbdd1c8a8c8a341a15ca6d13e63a5196439dec3e41bb"
metafile = true

[[files]]
file = "mods/create-contraption-terminals.pw.toml"
hash = "02d3c2c9758fe92e9010111553cbdc4edd009ffc543af0eac41b7b016a7047d1"
metafile = true

[[files]]
file = "mods/create-copper-zinc.pw.toml"
hash = "d1c2adb5b70e3252d1038a9ec80b6a23447053ad7507fd053f04d28703698e8e"
metafile = true

[[files]]
file = "mods/create-cyber-goggles.pw.toml"
hash = "7b285057ef04cd2999a2113fa1cdfd691ba40ae1dbfe9fdd051059651486404a"
metafile = true

[[files]]
file = "mods/create-deco.pw.toml"
hash = "87ccbd409962ea48348bd005f00a7c68d2add8528cdc6287c83ff52d21dc8c98"
metafile = true

[[files]]
file = "mods/create-deep-dark.pw.toml"
hash = "4f06f5a26c1a33a96301dc4888be6213fc208c96bb3fe002b499e39f6314c249"
metafile = true

[[files]]
file = "mods/create-design-n-decor.pw.toml"
hash = "bc4ef8bd7d32506703dcc175a62a12766addc393434ddbe8d17f01b071701943"
metafile = true

[[files]]
file = "mods/create-diesel-generators.pw.toml"
hash = "e424f248a40ef1ac0f10ce506bb24d493f57162313b1d732ec89ba20b2fc4bb9"
metafile = true

[[files]]
file = "mods/create-dragons-plus.pw.toml"
hash = "485c1d97761536a52331e5d50055ecd514086e2f23937f259e33e06cc638ca91"
metafile = true

[[files]]
file = "mods/create-dreams-and-desires.pw.toml"
hash = "80d8e54420806a0cfdc113dc559ae2e6bfa7dfcf44e176c7e230d7d371ca99e1"
metafile = true

[[files]]
file = "mods/create-dynamic-lights.pw.toml"
hash = "56ff7fa56eb6ae7d32cdd1f7ce84022d1ed25b416dd9142572ef0d2360d49ec9"
metafile = true

[[files]]
file = "mods/create-easy-goo.pw.toml"
hash = "73999bff2159ebeb0cffec6669fc268359c84c20359018bb72a1d99fc2a64bf0"
metafile = true

[[files]]
file = "mods/create-easy-structures.pw.toml"
hash = "1d91b46a5973bda84e2b314878693ef5df83475b95569a75b00de096edfe3df4"
metafile = true

[[files]]
file = "mods/create-encased.pw.toml"
hash = "7c07f70035a9ef0fa613bb1acab3db9377a7de11461761c4a33a52df71382c23"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "05995b86a58ee09106d8e34458a4eb7561ad5bf3e25d89f491519c18010afe8e"
metafile = true

[[files]]
file = "mods/create-framed.pw.toml"
hash = "0bfd51544f3b3f14e371edf38526a6f36227d660f00070adcd31b2a0db40b18e"
metafile = true

[[files]]
file = "mods/create-integrated-farming.pw.toml"
hash = "cd8d9ec31cd4c865ab3a2dc191a0109a03ccfe29a397d1489d0bc754f9345856"
metafile = true

[[files]]
file = "mods/create-let-the-adventure-begin.pw.toml"
hash = "51e6ff5e9cca2880c4644369fade514aebba69dd33120228fdc4df8ce0074794"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "637a0f8e81eebbb776d07f7ce32d6b67675000b6259beacec1cbb1b1d730683d"
metafile = true

[[files]]
file = "mods/create-ore-excavation.pw.toml"
hash = "5ddec1994ef29d1d176fca6e119dd09bb895b32f99df3ab49bae881d8d2eedd2"
metafile = true

[[files]]
file = "mods/create-pattern-schematics.pw.toml"
hash = "faddfa6807d11014c93bbfd8e543e8843e6d44e53f70d54e0b7e3e95766d2021"
metafile = true

[[files]]
file = "mods/create-power-loader.pw.toml"
hash = "ee76dbe108ebf5cf68047f60ecabee5aeb029015253dc82c007b941a6d6cfcdf"
metafile = true

[[files]]
file = "mods/create-stuff-additions.pw.toml"
hash = "7bdf3b6cbe0579a034372ce1eec83e3c1888134f19beb6b17fbf2005706453be"
metafile = true

[[files]]
file = "mods/create-trading-floor.pw.toml"
hash = "8d3dbde2773a667faab3131ec4e602f984be096f2e348aa116c7bdf23ee08aa9"
metafile = true

[[files]]
file = "mods/create-train-parts.pw.toml"
hash = "c8d8e3d2cbb61f6977d475b0203ad21ef0aab34409cdc304db87a7dd65fbeda1"
metafile = true

[[files]]
file = "mods/create-trainutilities.pw.toml"
hash = "70f4abe6b7351bab4fa130e15eac677e01a87ac4ab0348150590227de8343884"
metafile = true

[[files]]
file = "mods/create-ultimate-factory.pw.toml"
hash = "183370d2f76530fd297ec977f6e2941073fe6e0e9b9f8486cf5adc9956c6310e"
metafile = true

[[files]]
file = "mods/create-winery.pw.toml"
hash = "d0c1901b7bc305f52f8ccf9ff1155eb3e5653475bf99e9100917c856a1c812be"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "d6043c928c34ce1f4ada544a49193f95c281665cf88d4931e73370ea02870bed"
metafile = true

[[files]]
file = "mods/create_oxidized.pw.toml"
hash = "7e9e3d04c85d0a94a449245bae9239658e0fdeaf53043145c70d54070a38b9b0"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "84033f53f275811750cf65ca9ddb5ca0daeced93700ce025d2b834c115ae05f4"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "36fe638633083667b1fd66b53fd1e0d76467dec3a58062fede8207350bd6771d"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "3f8fb0012b658c3ed2dfcde1385aa6255ee46cd18b77975d68665aaf0ee2a94d"
metafile = true

[[files]]
file = "mods/dragonlib.pw.toml"
hash = "7f37f1846f25e9c4e9297ba1e06fe81584145f466eb5b3e45940717b0aeb3bbb"
metafile = true

[[files]]
file = "mods/explorify.pw.toml"
hash = "d93c3c494955dfc44e2590ded2ee8414d582e87f2fca00575f08576ae2197d57"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "44abae510395f12f9ea97b8296b2f72e25f18b9f3f2cc0ee42c0d9afd73fe0b3"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "05d96d5b17399f048469ff4b44451eb8d99cc7a2a075ff55718c397cb508b0c2"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "f67aa60c765593a8c70f78296a460349c6aef5f4a16d173eae02e8803b545ad4"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "e7d3f7e0472ba9a3ef946fa5defcb157e4126636e603c2306d4ad6065936d5e2"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "1a9ec5beaba1be3151b8710db2bfab90c2063a4dafaf2720336852245a145cc4"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "f199fe36b913131dfa2d31ec4a03186aa00be227f7fe2e34c4c3064b8601bb99"
metafile = true

[[files]]
file = "mods/mechanicals-lib.pw.toml"
hash = "02339d0e95b7fec78a21c9774faaba03521998804a4c047cd4913098eaac14a1"
metafile = true

[[files]]
file = "mods/ore-harvester.pw.toml"
hash = "d24b63a488c7807499b18fe76eda1ecd3ad8b787ded557f9a6412dadc66ba4d4"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "09306b955060349986ccf6a6d2a67f1e019fa172a7dc690dd6007f81c966309a"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "f527c21279cbfc2025d9cdf8267fe22cd43b42a2f994fc4ae0d76c069a844387"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
hash = "6b100c6847b82f48ac150816c2e9ce8fd590a4dc92a49e38634b7f6c6b5a2e71"
metafile = true

[[files]]
file = "mods/sodium-dynamic-lights.pw.toml"
hash = "c1e526d3d17cb3563e596d45c7567ed1fe60c31bdc3457f7a747ef8150bd3c1b"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "d193173f0f5dfb4a921d44e29e8d5cee656dd3a40872939069715bb482b66fc9"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "202471b4ee4257e6a3401680543a1986ae0bf163d0a9fed74f72e1929b46b5f7"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "da7ee99189ad35aac094919fe33cac647d98533b23c228f10d4811f08989e2b8"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
hash = "cdffc74140a6d0da190aebf074d7b0e1a2d7f0b0e4fa7803618d2f154c262a0b"
metafile = true

[[files]]
file = "mods/tree-harvester.pw.toml"
hash = "d5837bde6e12926d8649f6caaadf68a6f80e060ac164348d7ec5ec6555817165"
metafile = true

[[files]]
file = "mods/xaero-train-map.pw.toml"
hash = "055508f48abfc3dc9705337d324fe839bbc88cd5cd06ce77f65b4bd2c976a983"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "9d76c3683cfea5c5976823a000eacc9944db9f097894356d2a029cf36642ffa4"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "9b8940ac83dde84cfc59860c6544a4b1194e635786c26bd47dc15eee79e63598"
metafile = true
