name = "indpack"
author = "jzx333"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a487551e28d06873fbe53e8fb5b268e10b5aa7b185fd354cbc98374bb002e4fc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.214"
